import{createHash,randomBytes}from"node:crypto";
export const GOOGLE_AUTH_ENDPOINT="https://accounts.google.com/o/oauth2/v2/auth";
export const GOOGLE_TOKEN_ENDPOINT="https://oauth2.googleapis.com/token";
export function createPkcePair():{verifier:string;challenge:string}{const verifier=randomBytes(32).toString("base64url");return{verifier,challenge:createHash("sha256").update(verifier,"ascii").digest("base64url")}}
export function buildGoogleAuthUrl(input:{clientId:string;redirectUri:string;state:string;nonce:string;codeChallenge:string}):string{const url=new URL(GOOGLE_AUTH_ENDPOINT);url.searchParams.set("response_type","code");url.searchParams.set("client_id",input.clientId);url.searchParams.set("redirect_uri",input.redirectUri);url.searchParams.set("scope","openid email");url.searchParams.set("state",input.state);url.searchParams.set("nonce",input.nonce);url.searchParams.set("code_challenge",input.codeChallenge);url.searchParams.set("code_challenge_method","S256");url.searchParams.set("prompt","select_account");return url.toString()}
export type GoogleClaims={iss?:string;aud?:string;exp?:number;nonce?:string;sub?:string;email?:string;email_verified?:boolean};
export function decodeIdTokenClaims(idToken:string):GoogleClaims{const parts=idToken.split(".");if(parts.length!==3)throw new Error("GOOGLE_TOKEN_INVALID");try{return JSON.parse(Buffer.from(parts[1],"base64url").toString("utf8"))as GoogleClaims}catch{throw new Error("GOOGLE_TOKEN_INVALID")}}
export function validateGoogleClaims(input:{claims:GoogleClaims;clientId:string;nonce:string;now:Date}):{sub:string;email:string}{const{claims}=input;if(claims.iss!=="https://accounts.google.com"&&claims.iss!=="accounts.google.com")throw new Error("GOOGLE_TOKEN_INVALID");if(claims.aud!==input.clientId)throw new Error("GOOGLE_TOKEN_INVALID");if(typeof claims.exp!=="number"||claims.exp*1000<=input.now.getTime())throw new Error("GOOGLE_TOKEN_EXPIRED");if(!claims.nonce||claims.nonce!==input.nonce)throw new Error("GOOGLE_TOKEN_INVALID");if(!claims.sub)throw new Error("GOOGLE_TOKEN_INVALID");if(!claims.email||claims.email_verified!==true)throw new Error("GOOGLE_EMAIL_UNVERIFIED");return{sub:claims.sub,email:claims.email.trim().toLowerCase()}}
type FetchLike=(url:string,init:{method:string;headers:Record<string,string>;body:string})=>Promise<{ok:boolean;json():Promise<unknown>}>;
export async function exchangeGoogleCode(input:{code:string;codeVerifier:string;clientId:string;clientSecret:string;redirectUri:string;fetchImpl?:FetchLike}):Promise<{idToken:string}>{const fetchImpl=input.fetchImpl??(fetch as unknown as FetchLike);const body=new URLSearchParams({grant_type:"authorization_code",code:input.code,client_id:input.clientId,client_secret:input.clientSecret,redirect_uri:input.redirectUri,code_verifier:input.codeVerifier});const response=await fetchImpl(GOOGLE_TOKEN_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:body.toString()});if(!response.ok)throw new Error("GOOGLE_EXCHANGE_FAILED");const payload=await response.json()as{id_token?:string};if(!payload.id_token)throw new Error("GOOGLE_EXCHANGE_FAILED");return{idToken:payload.id_token}}
