import{describe,expect,it}from"vitest";import{buildGoogleAuthUrl,createPkcePair,decodeIdTokenClaims,exchangeGoogleCode,GOOGLE_TOKEN_ENDPOINT,validateGoogleClaims}from"./google";import{createHash}from"node:crypto";
const now=new Date("2026-07-11T18:00:00Z");
const claims=(overrides:Record<string,unknown>={})=>({iss:"https://accounts.google.com",aud:"client-1",exp:Math.floor(now.getTime()/1000)+300,nonce:"nonce-1",sub:"google-sub-1",email:"Player@Example.com",email_verified:true,...overrides});
const encode=(payload:Record<string,unknown>)=>`${Buffer.from("{}").toString("base64url")}.${Buffer.from(JSON.stringify(payload)).toString("base64url")}.signature`;
describe("Google OAuth",()=>{
it("creates an RFC 7636 S256 challenge from the verifier",()=>{const{verifier,challenge}=createPkcePair();expect(verifier).toMatch(/^[A-Za-z0-9_-]{43}$/);expect(challenge).toBe(createHash("sha256").update(verifier,"ascii").digest("base64url"));expect(createPkcePair().verifier).not.toBe(verifier)});
it("builds the authorization URL with PKCE, state, and nonce",()=>{const url=new URL(buildGoogleAuthUrl({clientId:"client-1",redirectUri:"https://club.mx/api/v1/auth/google/callback",state:"state-1",nonce:"nonce-1",codeChallenge:"challenge-1"}));expect(url.origin+url.pathname).toBe("https://accounts.google.com/o/oauth2/v2/auth");expect(Object.fromEntries(url.searchParams)).toEqual({response_type:"code",client_id:"client-1",redirect_uri:"https://club.mx/api/v1/auth/google/callback",scope:"openid email",state:"state-1",nonce:"nonce-1",code_challenge:"challenge-1",code_challenge_method:"S256",prompt:"select_account"})});
it("decodes ID token claims and rejects malformed tokens",()=>{expect(decodeIdTokenClaims(encode(claims())).sub).toBe("google-sub-1");expect(()=>decodeIdTokenClaims("only.two")).toThrow("GOOGLE_TOKEN_INVALID");expect(()=>decodeIdTokenClaims("a.!!!.c")).toThrow("GOOGLE_TOKEN_INVALID")});
it("accepts valid claims and normalizes the email",()=>{expect(validateGoogleClaims({claims:claims(),clientId:"client-1",nonce:"nonce-1",now})).toEqual({sub:"google-sub-1",email:"player@example.com"})});
it("rejects wrong issuer, audience, expiry, nonce, and unverified email",()=>{expect(()=>validateGoogleClaims({claims:claims({iss:"https://evil.example"}),clientId:"client-1",nonce:"nonce-1",now})).toThrow("GOOGLE_TOKEN_INVALID");expect(()=>validateGoogleClaims({claims:claims({aud:"other-client"}),clientId:"client-1",nonce:"nonce-1",now})).toThrow("GOOGLE_TOKEN_INVALID");expect(()=>validateGoogleClaims({claims:claims({exp:Math.floor(now.getTime()/1000)-1}),clientId:"client-1",nonce:"nonce-1",now})).toThrow("GOOGLE_TOKEN_EXPIRED");expect(()=>validateGoogleClaims({claims:claims({nonce:"other"}),clientId:"client-1",nonce:"nonce-1",now})).toThrow("GOOGLE_TOKEN_INVALID");expect(()=>validateGoogleClaims({claims:claims({email_verified:false}),clientId:"client-1",nonce:"nonce-1",now})).toThrow("GOOGLE_EMAIL_UNVERIFIED");expect(()=>validateGoogleClaims({claims:claims({sub:undefined}),clientId:"client-1",nonce:"nonce-1",now})).toThrow("GOOGLE_TOKEN_INVALID")});
it("exchanges the code with PKCE verifier and surfaces failures",async()=>{const requests:{url:string;body:string}[]=[];const fetchImpl=async(url:string,init:{body:string})=>{requests.push({url,body:init.body});return{ok:true,json:async()=>({id_token:"token-1"})}};const result=await exchangeGoogleCode({code:"code-1",codeVerifier:"verifier-1",clientId:"client-1",clientSecret:"secret-1",redirectUri:"https://club.mx/cb",fetchImpl:fetchImpl as never});expect(result.idToken).toBe("token-1");expect(requests[0].url).toBe(GOOGLE_TOKEN_ENDPOINT);expect(Object.fromEntries(new URLSearchParams(requests[0].body))).toEqual({grant_type:"authorization_code",code:"code-1",client_id:"client-1",client_secret:"secret-1",redirect_uri:"https://club.mx/cb",code_verifier:"verifier-1"});await expect(exchangeGoogleCode({code:"c",codeVerifier:"v",clientId:"i",clientSecret:"s",redirectUri:"r",fetchImpl:(async()=>({ok:false,json:async()=>({})}))as never})).rejects.toThrow("GOOGLE_EXCHANGE_FAILED");await expect(exchangeGoogleCode({code:"c",codeVerifier:"v",clientId:"i",clientSecret:"s",redirectUri:"r",fetchImpl:(async()=>({ok:true,json:async()=>({})}))as never})).rejects.toThrow("GOOGLE_EXCHANGE_FAILED")});
});
