import{database}from"../db/client";import{openSecret,sealSecret}from"./secret-box";import{generateTotpSecret,otpauthUri,verifyTotp}from"./totp";
export async function beginTotpEnrollment(input:{userId:string;authSecret:string;now:Date},sql=database()):Promise<{secret:string;otpauthUri:string}>{
return sql.begin(async tx=>{const users=await tx<{email:string}[]>`select email from users where id=${input.userId}`;if(!users.length)throw new Error("USER_NOT_FOUND");const rows=await tx<{activated_at:Date|null}[]>`select activated_at from user_totp_credentials where user_id=${input.userId} for update`;if(rows[0]?.activated_at)throw new Error("TOTP_ALREADY_ACTIVE");const secret=generateTotpSecret(),box=sealSecret(secret,input.authSecret);await tx`insert into user_totp_credentials(user_id,secret_box,activated_at,last_used_step,created_at,updated_at) values(${input.userId},${box},null,null,${input.now},${input.now}) on conflict(user_id) do update set secret_box=${box},activated_at=null,last_used_step=null,updated_at=${input.now}`;return{secret,otpauthUri:otpauthUri({secret,email:users[0].email})}});}
export async function activateTotp(input:{userId:string;sessionId:string;code:string;authSecret:string;now:Date},sql=database()):Promise<{activatedAt:Date}>{
return sql.begin(async tx=>{const rows=await tx<{secret_box:string;activated_at:Date|null}[]>`select secret_box,activated_at from user_totp_credentials where user_id=${input.userId} for update`;const row=rows[0];if(!row)throw new Error("TOTP_NOT_ENROLLED");if(row.activated_at)throw new Error("TOTP_ALREADY_ACTIVE");const{step}=verifyTotp({secret:openSecret(row.secret_box,input.authSecret),code:input.code,now:input.now});await tx`update user_totp_credentials set activated_at=${input.now},last_used_step=${step},updated_at=${input.now} where user_id=${input.userId}`;await tx`update sessions set step_up_verified_at=${input.now} where id=${input.sessionId} and revoked_at is null`;return{activatedAt:input.now}});}
export async function verifyTotpStepUp(input:{userId:string;sessionId:string;code:string;authSecret:string;now:Date},sql=database()):Promise<{verifiedAt:Date}>{
return sql.begin(async tx=>{const rows=await tx<{secret_box:string;activated_at:Date|null;last_used_step:number|null}[]>`select secret_box,activated_at,last_used_step from user_totp_credentials where user_id=${input.userId} for update`;const row=rows[0];if(!row?.activated_at)throw new Error("TOTP_ENROLLMENT_REQUIRED");const{step}=verifyTotp({secret:openSecret(row.secret_box,input.authSecret),code:input.code,now:input.now,lastUsedStep:row.last_used_step??undefined});await tx`update user_totp_credentials set last_used_step=${step},updated_at=${input.now} where user_id=${input.userId}`;await tx`update sessions set step_up_verified_at=${input.now} where id=${input.sessionId} and revoked_at is null`;return{verifiedAt:input.now}});}
export async function loadReviewGate(input:{userId:string;clubId:string},sql=database()):Promise<{staff:boolean;totpActive:boolean}>{
const rows=await sql<{staff:boolean;totp_active:boolean}[]>`select exists(select 1 from role_assignments where club_id=${input.clubId} and user_id=${input.userId} and role in ('owner','administrator')) as staff, exists(select 1 from user_totp_credentials where user_id=${input.userId} and activated_at is not null) as totp_active`;return{staff:rows[0].staff,totpActive:rows[0].totp_active}}
