import{createHash,randomBytes,timingSafeEqual}from"node:crypto";
export type MagicLinkToken={id:string;email:string;tokenHash:string;expiresAt:Date;usedAt?:Date};
export const hashToken=(token:string)=>createHash("sha256").update(token,"utf8").digest("hex");
export function issueMagicLink(input:{id:string;email:string;now:Date;ttlMinutes?:number}):{rawToken:string;record:MagicLinkToken}{const rawToken=randomBytes(32).toString("base64url"),ttl=input.ttlMinutes??15;return{rawToken,record:{id:input.id,email:input.email.trim().toLowerCase(),tokenHash:hashToken(rawToken),expiresAt:new Date(input.now.getTime()+ttl*60_000)}};}
export function consumeMagicLink(record:MagicLinkToken,rawToken:string,now:Date):MagicLinkToken{if(record.usedAt)throw new Error("TOKEN_ALREADY_USED");if(now>=record.expiresAt)throw new Error("TOKEN_EXPIRED");const provided=Buffer.from(hashToken(rawToken),"hex"),expected=Buffer.from(record.tokenHash,"hex");if(provided.length!==expected.length||!timingSafeEqual(provided,expected))throw new Error("TOKEN_INVALID");return{...record,usedAt:now};}
export type Session={id:string;userId:string;tokenHash:string;expiresAt:Date;revokedAt?:Date;lastSeenAt:Date;requiresStepUp:boolean};
export function issueSession(input:{id:string;userId:string;now:Date;days?:number;requiresStepUp?:boolean}){const rawToken=randomBytes(32).toString("base64url");return{rawToken,session:{id:input.id,userId:input.userId,tokenHash:hashToken(rawToken),expiresAt:new Date(input.now.getTime()+(input.days??30)*86_400_000),lastSeenAt:input.now,requiresStepUp:input.requiresStepUp??false} satisfies Session};}
export function validateSession(session:Session,rawToken:string,now:Date){if(session.revokedAt)throw new Error("SESSION_REVOKED");if(now>=session.expiresAt)throw new Error("SESSION_EXPIRED");const valid=hashToken(rawToken),a=Buffer.from(valid,"hex"),b=Buffer.from(session.tokenHash,"hex");if(a.length!==b.length||!timingSafeEqual(a,b))throw new Error("SESSION_INVALID");return session;}
export const revokeSession=(session:Session,now:Date):Session=>session.revokedAt?session:{...session,revokedAt:now};
