import{describe,expect,it}from"vitest";import{decodeBase32,encodeBase32,generateTotpSecret,otpauthUri,totpCode,totpStep,verifyTotp}from"./totp";
const rfcSecret="GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ";
describe("TOTP",()=>{
it("round-trips base32 and rejects invalid characters",()=>{expect(decodeBase32(rfcSecret).toString("utf8")).toBe("12345678901234567890");expect(encodeBase32(Buffer.from("12345678901234567890","utf8"))).toBe(rfcSecret);expect(decodeBase32(encodeBase32(Buffer.from([255,0,128,7,63]))).equals(Buffer.from([255,0,128,7,63]))).toBe(true);expect(()=>decodeBase32("ABC1!")).toThrow("TOTP_SECRET_INVALID");expect(()=>decodeBase32("")).toThrow("TOTP_SECRET_INVALID")});
it("matches the RFC 6238 SHA-1 reference vectors",()=>{const vectors:[number,string][]=[[59,"94287082"],[1111111109,"07081804"],[1234567890,"89005924"],[2000000000,"69279037"],[20000000000,"65353130"]];for(const[seconds,expected]of vectors)expect(totpCode(rfcSecret,totpStep(new Date(seconds*1000)),8)).toBe(expected)});
it("generates distinct 160-bit base32 secrets",()=>{const first=generateTotpSecret(),second=generateTotpSecret();expect(first).toMatch(/^[A-Z2-7]{32}$/);expect(first).not.toBe(second)});
it("accepts the current code and the adjacent window only",()=>{const now=new Date("2026-07-11T18:00:15Z"),step=totpStep(now);expect(verifyTotp({secret:rfcSecret,code:totpCode(rfcSecret,step),now}).step).toBe(step);expect(verifyTotp({secret:rfcSecret,code:totpCode(rfcSecret,step-1),now}).step).toBe(step-1);expect(verifyTotp({secret:rfcSecret,code:totpCode(rfcSecret,step+1),now}).step).toBe(step+1);expect(()=>verifyTotp({secret:rfcSecret,code:totpCode(rfcSecret,step-2),now})).toThrow("TOTP_CODE_INVALID")});
it("rejects malformed and incorrect codes",()=>{const now=new Date("2026-07-11T18:00:15Z");expect(()=>verifyTotp({secret:rfcSecret,code:"12345",now})).toThrow("TOTP_CODE_INVALID");expect(()=>verifyTotp({secret:rfcSecret,code:"abcdef",now})).toThrow("TOTP_CODE_INVALID");expect(()=>verifyTotp({secret:rfcSecret,code:"000000",now,windowSteps:0})).toThrow("TOTP_CODE_INVALID")});
it("rejects replayed codes at or before the last used step",()=>{const now=new Date("2026-07-11T18:00:15Z"),step=totpStep(now),code=totpCode(rfcSecret,step);expect(()=>verifyTotp({secret:rfcSecret,code,now,lastUsedStep:step})).toThrow("TOTP_CODE_REPLAYED");expect(()=>verifyTotp({secret:rfcSecret,code,now,lastUsedStep:step+3})).toThrow("TOTP_CODE_REPLAYED");expect(verifyTotp({secret:rfcSecret,code,now,lastUsedStep:step-1}).step).toBe(step)});
it("builds an otpauth URI with escaped issuer and account",()=>{const uri=otpauthUri({secret:rfcSecret,email:"admin@club.mx"});expect(uri).toBe(`otpauth://totp/Punto:admin%40club.mx?secret=${rfcSecret}&issuer=Punto&algorithm=SHA1&digits=6&period=30`)});
});
