import{createHmac,randomBytes,timingSafeEqual}from"node:crypto";
const ALPHABET="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
export function encodeBase32(bytes:Buffer):string{let bits=0,value=0,output="";for(const byte of bytes){value=(value<<8)|byte;bits+=8;while(bits>=5){output+=ALPHABET[(value>>>(bits-5))&31];bits-=5}}if(bits>0)output+=ALPHABET[(value<<(5-bits))&31];return output}
export function decodeBase32(secret:string):Buffer{const clean=secret.toUpperCase().replace(/=+$/,"").replace(/\s/g,"");if(!clean)throw new Error("TOTP_SECRET_INVALID");let bits=0,value=0;const bytes:number[]=[];for(const char of clean){const index=ALPHABET.indexOf(char);if(index<0)throw new Error("TOTP_SECRET_INVALID");value=(value<<5)|index;bits+=5;if(bits>=8){bytes.push((value>>>(bits-8))&255);bits-=8}}return Buffer.from(bytes)}
export const generateTotpSecret=()=>encodeBase32(randomBytes(20));
export const totpStep=(now:Date,stepSeconds=30)=>Math.floor(now.getTime()/1000/stepSeconds);
export function totpCode(secret:string,step:number,digits=6):string{const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(step));const digest=createHmac("sha1",decodeBase32(secret)).update(counter).digest();const offset=digest[digest.length-1]&15;return((digest.readUInt32BE(offset)&0x7fffffff)%10**digits).toString().padStart(digits,"0")}
export function verifyTotp(input:{secret:string;code:string;now:Date;lastUsedStep?:number;windowSteps?:number;digits?:number}):{step:number}{const digits=input.digits??6,window=input.windowSteps??1,current=totpStep(input.now);if(!new RegExp(`^\\d{${digits}}$`).test(input.code))throw new Error("TOTP_CODE_INVALID");let matched:number|undefined;for(let step=current-window;step<=current+window;step++){const expected=Buffer.from(totpCode(input.secret,step,digits),"utf8"),provided=Buffer.from(input.code,"utf8");if(expected.length===provided.length&&timingSafeEqual(expected,provided))matched=step}if(matched===undefined)throw new Error("TOTP_CODE_INVALID");if(input.lastUsedStep!==undefined&&matched<=input.lastUsedStep)throw new Error("TOTP_CODE_REPLAYED");return{step:matched}}
export function otpauthUri(input:{secret:string;email:string;issuer?:string}):string{const issuer=input.issuer??"Punto";return`otpauth://totp/${encodeURIComponent(issuer)}:${encodeURIComponent(input.email)}?secret=${input.secret}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=6&period=30`}
