"use client";
import { useEffect, useState } from "react";
type Applicant = { id: string; name: string; email: string; level: string; side: string; hand: string; submitted: string };
const demo: Applicant[] = [{ id: "1", name: "Mariana Silva", email: "mariana@example.com", level: "Intermedio", side: "Derecho", hand: "Derecha", submitted: "Hace 2 horas" }, { id: "2", name: "Ricardo Pérez", email: "ricardo@example.com", level: "Principiante", side: "Cualquiera", hand: "Izquierda", submitted: "Ayer" }, { id: "3", name: "Fernanda Ortiz", email: "fernanda@example.com", level: "Avanzado", side: "Izquierdo", hand: "Derecha", submitted: "Hace 2 días" }];

export function ReviewQueue() {
  const [items, setItems] = useState(demo), [selected, setSelected] = useState<string | undefined>(demo[0].id), [level, setLevel] = useState(""), [rejecting, setRejecting] = useState(false), [reason, setReason] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const clubId = process.env.NEXT_PUBLIC_CLUB_ID;
  useEffect(() => { if (!clubId) return; fetch(`/api/v1/clubs/${clubId}/applications`, { cache: "no-store" }).then(async response => { if (!response.ok) throw new Error(response.status === 401 ? "Tu sesión terminó." : "No pudimos cargar las solicitudes."); const payload = await response.json(); const loaded: Applicant[] = payload.data.map((item: { id: string; fullName: string; email: string; selfAssessedLevel?: string; preferredSide?: string; dominantHand?: string; submittedAt: string }) => ({ id: item.id, name: item.fullName, email: item.email, level: item.selfAssessedLevel ?? "Sin indicar", side: item.preferredSide ?? "Sin preferencia", hand: item.dominantHand ?? "Sin indicar", submitted: new Date(item.submittedAt).toLocaleDateString("es-MX") })); setItems(loaded); setSelected(loaded[0]?.id); }).catch(cause => setError(cause.message)); }, [clubId]);
  const current = items.find(item => item.id === selected);
  async function decide(decision: "approved" | "rejected") { if (!current || busy) return; setBusy(true); setError(""); if (!clubId) { remove(); setBusy(false); return; } try { const body = decision === "approved" ? { decision, levelCode: level.toLowerCase() } : { decision, reason }; const response = await fetch(`/api/v1/clubs/${clubId}/applications/${current.id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(response.status === 403 ? "No tienes permiso para revisar solicitudes." : "No pudimos guardar la decisión."); remove(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos guardar la decisión."); } finally { setBusy(false); } }
  function remove() { const remaining = items.filter(item => item.id !== selected); setItems(remaining); setSelected(remaining[0]?.id); setLevel(""); setRejecting(false); setReason(""); }
  if (!current) return <div className="empty-queue"><span>✓</span><h2>No hay solicitudes pendientes</h2><p>{error || "La cola está al día."}</p></div>;
  return <div className="review-layout"><aside><div className="queue-title"><strong>Pendientes</strong><span>{items.length}</span></div>{items.map(item => <button className={item.id === selected ? "active" : ""} key={item.id} onClick={() => { setSelected(item.id); setLevel(""); setRejecting(false); }}><b>{item.name.split(" ").map(name => name[0]).join("")}</b><span><strong>{item.name}</strong><small>{item.level} · {item.submitted}</small></span></button>)}</aside><section className="applicant-detail"><div className="applicant-head"><span>{current.name.split(" ").map(name => name[0]).join("")}</span><div><h2>{current.name}</h2><p>{current.email}</p></div><b>Pendiente</b></div><div className="detail-grid"><div><small>NIVEL DECLARADO</small><strong>{current.level}</strong></div><div><small>LADO PREFERIDO</small><strong>{current.side}</strong></div><div><small>MANO DOMINANTE</small><strong>{current.hand}</strong></div><div><small>SOLICITUD</small><strong>{current.submitted}</strong></div></div><div className="level-decision"><label>Nivel verificado<select value={level} onChange={event => setLevel(event.target.value)}><option value="">Selecciona después de revisar</option><option value="beginner">Principiante</option><option value="intermediate">Intermedio</option><option value="advanced">Avanzado</option></select></label>{level && <div><span>Rating inicial</span><strong>{level === "beginner" ? "1,100" : level === "intermediate" ? "1,500" : "1,900"}</strong><small>Provisional · desviación 350</small></div>}</div>{error && <p className="score-error" role="alert">{error}</p>}{rejecting ? <div className="reject-box"><label>Motivo del rechazo<textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Explica la decisión para el registro de auditoría." /></label><div><button onClick={() => setRejecting(false)}>Cancelar</button><button disabled={reason.trim().length < 8 || busy} onClick={() => decide("rejected")}>{busy ? "Guardando…" : "Confirmar rechazo"}</button></div></div> : <div className="decision-actions"><button onClick={() => setRejecting(true)}>Rechazar</button><button disabled={!level || busy} onClick={() => decide("approved")}>{busy ? "Guardando…" : "Aprobar y asignar nivel"}</button></div>}<p className="audit-caption">La decisión, el nivel, el responsable y la hora quedarán registrados en el historial de auditoría.</p></section></div>;
}
