import{describe,expect,it}from"vitest";import{prepareEventDraft,slugify,zonedTimeToUtc,type EventDraftInput}from"./create";
const now=new Date("2026-07-12T12:00:00Z");
const base:EventDraftInput={name:"Americano del Viernes",date:"2026-07-17",startTime:"18:00",endTime:"22:00",timeZone:"America/Matamoros",format:"americano",capacity:16,courts:4,minutesPerRound:20,now};
describe("event draft preparation",()=>{
it("slugifies names with accents and symbols",()=>{expect(slugify("Rincón del Bosque #1")).toBe("rincon-del-bosque-1");expect(slugify("  Torneo   ÑOÑO  ")).toBe("torneo-nono");expect(()=>slugify("¡¡¡")).toThrow("EVENT_NAME_REQUIRED")});
it("converts club-local times to UTC across DST",()=>{expect(zonedTimeToUtc("2026-07-17","18:00","America/Matamoros").toISOString()).toBe("2026-07-17T23:00:00.000Z");expect(zonedTimeToUtc("2026-01-16","18:00","America/Matamoros").toISOString()).toBe("2026-01-17T00:00:00.000Z");expect(zonedTimeToUtc("2026-07-17","18:00","America/Mexico_City").toISOString()).toBe("2026-07-18T00:00:00.000Z")});
it("prepares a valid draft with a General category",()=>{const draft=prepareEventDraft(base);expect(draft).toEqual({name:"Americano del Viernes",slug:"americano-del-viernes",startsAt:new Date("2026-07-17T23:00:00Z"),endsAt:new Date("2026-07-18T03:00:00Z"),category:{name:"General",format:"americano",capacity:16,configuration:{courts:4,minutesPerRound:20}}})});
it("rejects invalid names, dates, formats, and ranges",()=>{expect(()=>prepareEventDraft({...base,name:"  "})).toThrow("EVENT_NAME_REQUIRED");expect(()=>prepareEventDraft({...base,name:"x".repeat(81)})).toThrow("EVENT_NAME_TOO_LONG");expect(()=>prepareEventDraft({...base,date:"17/07/2026"})).toThrow("EVENT_DATE_INVALID");expect(()=>prepareEventDraft({...base,startTime:"6pm"})).toThrow("EVENT_TIME_INVALID");expect(()=>prepareEventDraft({...base,format:"padelazo" as never})).toThrow("EVENT_FORMAT_INVALID");expect(()=>prepareEventDraft({...base,capacity:3})).toThrow("EVENT_CAPACITY_INVALID");expect(()=>prepareEventDraft({...base,capacity:129})).toThrow("EVENT_CAPACITY_INVALID");expect(()=>prepareEventDraft({...base,courts:0})).toThrow("EVENT_COURTS_INVALID");expect(()=>prepareEventDraft({...base,minutesPerRound:5})).toThrow("EVENT_DURATION_INVALID")});
it("rejects inverted times and past events",()=>{expect(()=>prepareEventDraft({...base,endTime:"17:00"})).toThrow("EVENT_END_BEFORE_START");expect(()=>prepareEventDraft({...base,date:"2026-07-01"})).toThrow("EVENT_IN_PAST")});
});
