export type Channel="in_app"|"email"|"push";
export type NotificationType="application_approved"|"registration_confirmed"|"waitlist_promoted"|"schedule_published"|"court_changed"|"score_confirmation_required"|"score_disputed"|"rating_updated";
export type Preference={enabled:Record<Channel,boolean>;quietStart?:number;quietEnd?:number;timezoneOffsetMinutes:number};
export type OutboxMessage={id:string;deduplicationKey:string;userId:string;type:NotificationType;channel:Channel;payload:Record<string,unknown>;deliverAfter:Date;status:"pending"};
const channels:Channel[]=["in_app","email","push"];
function inQuietHour(hour:number,start:number,end:number){return start<end?hour>=start&&hour<end:hour>=start||hour<end;}
function afterQuietHours(now:Date,p:Preference){if(p.quietStart===undefined||p.quietEnd===undefined)return now;const local=new Date(now.getTime()+p.timezoneOffsetMinutes*60_000);if(!inQuietHour(local.getUTCHours(),p.quietStart,p.quietEnd))return now;const target=new Date(local);target.setUTCHours(p.quietEnd,0,0,0);if(target<=local)target.setUTCDate(target.getUTCDate()+1);return new Date(target.getTime()-p.timezoneOffsetMinutes*60_000);}
export function createNotificationMessages(input:{eventId:string;userId:string;type:NotificationType;payload:Record<string,unknown>;now:Date;preference:Preference;urgent?:boolean}):OutboxMessage[]{return channels.filter(c=>input.preference.enabled[c]).map(channel=>({id:`${input.eventId}:${input.userId}:${channel}`,deduplicationKey:`${input.eventId}:${input.userId}:${channel}`,userId:input.userId,type:input.type,channel,payload:input.payload,deliverAfter:input.urgent||channel==="in_app"?input.now:afterQuietHours(input.now,input.preference),status:"pending"}));}
export function claimDeliveries(messages:OutboxMessage[],now:Date,alreadySent:Set<string>){const seen=new Set<string>();return messages.filter(m=>m.status==="pending"&&m.deliverAfter<=now&&!alreadySent.has(m.deduplicationKey)&&!seen.has(m.deduplicationKey)&&(seen.add(m.deduplicationKey),true));}
