"use client";
import { useState } from "react";

export function SignInForm({ googleEnabled = false }: { googleEnabled?: boolean }) {
  const [email, setEmail] = useState(""), [sent, setSent] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); if (busy) return; setBusy(true); setError(""); try { const response = await fetch("/api/v1/auth/magic-link/request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, redirectTo: "/" }) }); if (!response.ok) throw new Error("REQUEST_FAILED"); setSent(true); } catch { setError("No pudimos solicitar el enlace. Revisa tu conexión e intenta nuevamente."); } finally { setBusy(false); } }
  if (sent) return <div className="signin-sent"><span>✉</span><h2>Revisa tu correo</h2><p>Si <strong>{email}</strong> puede iniciar sesión, recibirá un enlace válido durante 15 minutos.</p><button onClick={() => { setSent(false); setError(""); }}>Usar otra dirección</button></div>;
  return <form className="signin-form" onSubmit={submit}><label>Correo electrónico<input required type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="tu@correo.com" /></label>{error && <p className="score-error" role="alert">{error}</p>}<button disabled={busy}>{busy ? "Enviando…" : "Continuar con correo"}</button><div className="or"><span>o</span></div>{googleEnabled ? <a className="google-button" href="/api/v1/auth/google/start"><b>G</b> Continuar con Google</a> : <button type="button" className="google-button" disabled><b>G</b> Google disponible próximamente</button>}<p>Al continuar aceptas el aviso de privacidad. Tener una cuenta no concede automáticamente membresía del club.</p></form>;
}
