import { NextRequest, NextResponse } from "next/server";
import { playerApplicationSchema } from "@/server/players/validation";
import { readCookie, requireSameOrigin } from "@/server/http/security";
import { resolveSession } from "@/server/auth/postgres-session";
import { createClubApplication } from "@/server/applications/postgres-repository";
import { listPendingApplications } from "@/server/applications/postgres-queue";

async function authenticated(request: NextRequest) { const token = readCookie(request.headers.get("cookie"), "punto_session"); return token ? resolveSession(token) : null; }
export async function GET(request: NextRequest, { params }: { params: Promise<{ clubId: string }> }) { const session = await authenticated(request); if (!session) return error("UNAUTHENTICATED", 401); try { const { clubId } = await params; const items = await listPendingApplications({ clubId, actorUserId: session.userId }); return NextResponse.json({ data: items }, { headers: { "Cache-Control": "private, no-store", "Vary": "Cookie" } }); } catch (cause) { return error(cause instanceof Error && cause.message === "FORBIDDEN" ? "FORBIDDEN" : "INTERNAL_ERROR", cause instanceof Error && cause.message === "FORBIDDEN" ? 403 : 500); } }
export async function POST(request: NextRequest, { params }: { params: Promise<{ clubId: string }> }) { try { const appUrl = process.env.APP_URL; if (!appUrl) throw new Error("SERVER_CONFIGURATION_ERROR"); requireSameOrigin({ origin: request.headers.get("origin"), appUrl }); const session = await authenticated(request); if (!session) return error("UNAUTHENTICATED", 401); const parsed = playerApplicationSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: { code: "VALIDATION_ERROR", message: "Revisa los datos de la solicitud.", fieldErrors: parsed.error.flatten().fieldErrors } }, { status: 422 }); const { clubId } = await params; const result = await createClubApplication({ id: crypto.randomUUID(), profileId: crypto.randomUUID(), clubId, userId: session.userId, fullName: parsed.data.fullName, preferredLocale: parsed.data.preferredLocale, selfAssessedLevel: parsed.data.selfAssessedLevel, dominantHand: parsed.data.dominantHand, preferredSide: parsed.data.preferredSide, now: new Date() }); return NextResponse.json({ data: result }, { status: 201, headers: { "Cache-Control": "no-store" } }); } catch (cause) { const code = cause instanceof Error ? cause.message : "INTERNAL_ERROR"; if (code === "ACTIVE_APPLICATION_EXISTS") return error(code, 409); if (code === "ORIGIN_REQUIRED" || code === "INVALID_ORIGIN") return error("FORBIDDEN", 403); if (code === "SERVER_CONFIGURATION_ERROR") return error(code, 503); return error("INTERNAL_ERROR", 500); } }
function error(code: string, status: number) { return NextResponse.json({ error: { code, message: code === "UNAUTHENTICATED" ? "Inicia sesión para continuar." : code === "FORBIDDEN" ? "No tienes permiso para ver estas solicitudes." : code === "ACTIVE_APPLICATION_EXISTS" ? "Ya existe una solicitud activa." : "No fue posible procesar la solicitud." } }, { status, headers: { "Cache-Control": "no-store" } }); }
